language: java

jdk: oraclejdk8

dist: trusty

matrix:
  include:
    - os: linux
      jdk: oraclejdk8

# Input the path to your pom.xml in the projects you wanna Travis:
script:
  - mvn -q -B -f Week39/Thursday/Backend/pom.xml clean verify

